// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// get_trial_dat
arma::mat get_trial_dat(const Rcpp::List& cfg);
RcppExport SEXP _OrvacRCT_get_trial_dat(SEXP cfgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type cfg(cfgSEXP);
    rcpp_result_gen = Rcpp::wrap(get_trial_dat(cfg));
    return rcpp_result_gen;
END_RCPP
}
// get_interims
arma::mat get_interims(const arma::mat& d, const Rcpp::List& cfg);
RcppExport SEXP _OrvacRCT_get_interims(SEXP dSEXP, SEXP cfgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type cfg(cfgSEXP);
    rcpp_result_gen = Rcpp::wrap(get_interims(d, cfg));
    return rcpp_result_gen;
END_RCPP
}
// nothing_much
void nothing_much();
RcppExport SEXP _OrvacRCT_nothing_much() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    nothing_much();
    return R_NilValue;
END_RCPP
}
// test_trial1
void test_trial1();
RcppExport SEXP _OrvacRCT_test_trial1() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_trial1();
    return R_NilValue;
END_RCPP
}
// test_trial2
void test_trial2();
RcppExport SEXP _OrvacRCT_test_trial2() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_trial2();
    return R_NilValue;
END_RCPP
}
// test_trial3
void test_trial3();
RcppExport SEXP _OrvacRCT_test_trial3() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_trial3();
    return R_NilValue;
END_RCPP
}
// test_trial4
void test_trial4();
RcppExport SEXP _OrvacRCT_test_trial4() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_trial4();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OrvacRCT_get_trial_dat", (DL_FUNC) &_OrvacRCT_get_trial_dat, 1},
    {"_OrvacRCT_get_interims", (DL_FUNC) &_OrvacRCT_get_interims, 2},
    {"_OrvacRCT_nothing_much", (DL_FUNC) &_OrvacRCT_nothing_much, 0},
    {"_OrvacRCT_test_trial1", (DL_FUNC) &_OrvacRCT_test_trial1, 0},
    {"_OrvacRCT_test_trial2", (DL_FUNC) &_OrvacRCT_test_trial2, 0},
    {"_OrvacRCT_test_trial3", (DL_FUNC) &_OrvacRCT_test_trial3, 0},
    {"_OrvacRCT_test_trial4", (DL_FUNC) &_OrvacRCT_test_trial4, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_OrvacRCT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
