# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_trial <- function(idxsim, cfg, rtn_trial_dat) {
    .Call(`_OrvacRCT_simulate_trial`, idxsim, cfg, rtn_trial_dat)
}

