# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_trial_dat <- function(cfg) {
    .Call(`_OrvacRCT_get_trial_dat`, cfg)
}

nothing_much <- function() {
    invisible(.Call(`_OrvacRCT_nothing_much`))
}

test_trial1 <- function() {
    invisible(.Call(`_OrvacRCT_test_trial1`))
}

test_trial2 <- function() {
    invisible(.Call(`_OrvacRCT_test_trial2`))
}

test_trial3 <- function() {
    invisible(.Call(`_OrvacRCT_test_trial3`))
}

test_trial4 <- function() {
    invisible(.Call(`_OrvacRCT_test_trial4`))
}

