# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_interims <- function(cfg) {
    .Call(`_OrvacRCT_get_interims`, cfg)
}

test_set_state <- function(cfg, n_target, ref_time, dofu, cur_intrm) {
    .Call(`_OrvacRCT_test_set_state`, cfg, n_target, ref_time, dofu, cur_intrm)
}

simulate_trial <- function(idxsim, cfg, rtn_trial_dat) {
    .Call(`_OrvacRCT_simulate_trial`, idxsim, cfg, rtn_trial_dat)
}

